version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
